# Themes are encouraged to use these universal variables
# so be sure to set them if your theme uses them.
title: &uname boechat107
name: Andre Boechat
email: &aemail boechat107@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    Blog from Andre Boechat including notes about software and some other stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: &urlsite "https://boechat107.github.io"
github_username: boechat107
twitter_username: boechat107

# Theme configuration:
remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: dirt

# Outputting
permalink: /:year-:month/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
path: /tags/

words_per_minute: 100
search: true

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true


# Site Author
author:
  name             : "Andre Ambrosio Boechat"
  avatar           : "/images/avatar5.jpg"
  bio              : "Software engineer with experience in web services, machine learning and computer vision. I'm also becoming very good at changing diapers!"
  location         : "Florianopolis, Brazil"
  email            : *aemail
  uri              : *urlsite
  home             : # null (default), "absolute or relative url to link to author home"
  bitbucket        :
  github           : *uname
  gitlab           :
  linkedin         : *uname
  stackoverflow    : "747872/boechat107"
  twitter          : *uname

social:
  type: # Person or Organization (defaults to Person)
  name: # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles
    - https://www.linkedin.com/in/boechat107/
    - https://github.com/boechat107
    - http://www.goodreads.com/boechat107
    - https://twitter.com/boechat107

analytics:
    provider: google
    google:
        tracking_id: 'UA-23191338-3'

# Reading Files
include:
  - .htaccess
  - images
  - _pages
exclude:
  - Gemfile
  - README
keep_files:
    - .git
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
